--- #YAML:1.0
name: Params-Style
version: 0.03
license: perl
distribution_type: module
requires:
  Attribute::Handlers: 0
  Test::More: 0
  Tie::Hash: 0
recommends: {}
build_requires: {}
conflicts: {}
provides: {}
generated_by: Module::Build version 0.19
